// styleguide/vue/src/pages/Login/index.vue
<script>
  import model from '@startupjs/model'
  import { Input, Button } from '../../components'

  export default {
    components: { Input, Button },
    methods: {
      onSubmit() {
        if (!this.user.login) return

        this.user.id = model.id()
        localStorage.setItem('user', JSON.stringify(this.user))

        model.scope('users').add(this.user)
        window.location.pathname = '/'
      }
    },
    data: ()=> ({
      user: { id: '', login: '' }
    })
  }
</script>

<template>
  <div :class="$style.login">
    <Input
      placeholder="Write login"
      v-model="user.login"
    />
    <Button
      :class="$style.loginButton"
      @click="onSubmit"
    >Login</Button>
  </div>
</template>

<style module>
  .login {
    display: flex;
    width: 100%;
    height: 100vh;
    justify-content: center;
    align-items: center;
  }
  .loginButton {
    margin-left: 8px;
  }
</style>

// styleguide/svelte/src/pages/Login/index.svelte
<script>
  import model from '@startupjs/model'
  import { Input, Button } from '../../components'

  const user = { id: '', login: '' }

  function onSubmit () {
    if (!user.login) return

    user.id = model.id()
    localStorage.setItem('user', JSON.stringify(user))

    model.scope('users').add(user)
    window.location.pathname = '/'
  }
</script>

<div class="root">
  <Input
    placeholder="Write login"
    bind:value={user.login}
  />
  <Button
    class="loginButton"
    on:click={onSubmit}
  >Login</Button>
</div>

<style>
  :global(.loginButton) {
    margin-left: 8px;
  }
  .root {
    display: flex;
    width: 100%;
    height: 100%;
    justify-content: center;
    align-items: center;
  }
</style>
