// styleguide/vue/src/pages/CreateRoom/index.vue
<script>
  import model from '@startupjs/model'
  import { Input, Button } from '../../components'

  const user = JSON.parse(localStorage.getItem('user'))

  export default {
    name: 'page-create-room',
    components: { Button, Input },
    methods: {
      onSubmit() {
        if (!this.name) return
        model.scope('rooms').add({
          userId: this.userId,
          name: this.name
        })
        this.$router.push({ name: 'home' })
      }
    },
    data: ()=> ({
      userId: user.id,
      name: ''
    })
  }
</script>

<template>
  <div :class="$style.createRoom">
    <Input
      placeholder="Room name"
      v-model="name"
    />

    <Button
      :class="$style.buttonCreate"
      @click="onSubmit"
    >Create</Button>
  </div>
</template>

<style module>
  .buttonCreate {
    margin-top: 8px;
  }
  .createRoom {
    margin-top: 16px;
  }
</style>

// styleguide/svelte/src/pages/CreateRoom/index.svelte
<script>
  import model from '@startupjs/model'
  import { getContext } from 'svelte'
  import { navigate } from 'svelte-routing'
  import { Input, Button } from '../../components'

  let data = {
    userId: getContext('user').id
  }

  function onSubmit () {
    if (!data.name) return

    model.scope('rooms').add(data)
    navigate('/')
  }
</script>

<div class="root">
  <Input
    placeholder="Room name"
    bind:value={data.name}
  />
  <Button
    class="buttonCreate"
    on:click={onSubmit}
  >Create</Button>
</div>

<style>
  :global(.buttonCreate) {
    margin-top: 8px;
  }

  .root {
    margin-top: 16px;
  }
</style>
