// styleguide/vue/src/pages/Room/index.vue
<script>
  import { watch, onUnmounted, onMounted, computed } from 'vue'
  import { useRoute } from 'vue-router'
  import { useDoc, useQuery } from '../../helpers'

  const user = JSON.parse(localStorage.getItem('user') || '{}')

  export default {
    name: 'page-room',
    setup (props, context) {
      const route = useRoute()
      const room = useDoc('rooms', route.params.roomId)
      const users = computed(()=> useQuery('users', {
        _id: { $in: room.value?.userIds }
      }))

      onMounted(()=> {
        setTimeout(()=> onReset(), 5000)
      })
      onUnmounted(()=> onReset())
      function onReset () {
        const userIndex = room.value.userIds.findIndex(id => id === user.id)
        if (userIndex === -1) return
        room.value.$.remove('userIds', userIndex)
      }

      watch(room, (room, prev) => {
        if (prev === null && room) {
          if (!room.userIds) room.$.set('userIds', [])
          const userIndex = room.userIds.findIndex(id => id === user.id)
          if (userIndex !== -1) return
          room.$.push('userIds', user.id)
        }
      })

      return { room, users }
    }
  }
</script>

<template>
  <div v-if="users.value" :class="$style.root">
    Online {{users.value.length}}: {{users.value.map(user=> user.login).join(', ')}}

    {{room}}
  </div>
</template>

<style module>
  .root {
    margin-top: 16px;
    display: flex;
    flex-direction: column;
  }
</style>

// styleguide/svelte/src/pages/Room/index.svelte
<script>
  import { onDestroy, getContext } from 'svelte'
  import { racerQuery, racerDoc } from '../../helpers'

  export let roomId = ''

  const userId = getContext('user').id // storeSession
  const room$ = racerDoc('rooms', roomId)
  $: users$ = racerQuery('users', { _id: { $in: $room$?.userIds } })
  $: messages$ = racerQuery('messages', { roomId: $room$?.id })

  room$.onSubscribe = ()=> {
    if (!$room$.userIds) room$.set('userIds', [])
    room$.push('userIds', userId)
  }

  onDestroy(()=> onReset())

  function onReset () {
    const room = room$.get()
    const userIndex = room.userIds.findIndex(id => id === userId)
    if (userIndex === -1) return
    room$.remove('userIds', userIndex)
  }
</script>

<svelte:window on:beforeunload={onReset} />

<div class="root">
  Online {$users$?.length}: {$users$?.map(user=> user.login)}

  <div></div>

  <input />
</div>

<style>
  .root {
    margin-top: 16px;
    display: flex;
    flex-direction: column;
  }
</style>
