// styleguide/svelte/src/App.svelte
<script>
  import { setContext } from 'svelte'
  import { Router, Route, navigate } from 'svelte-routing'
  import { Rooms, CreateRoom, Room, Login } from './pages'
  import { Header, Content } from './components'

  export let url = ''

  const user = JSON.parse(localStorage.getItem('user') || '{}')
  if (!user.id) navigate('/login')

  setContext('user', user)
</script>

<Router url={url}>
  {#if user.id}
    <Header />
    <main>
      <Content>
        <Route path="/" component={Rooms} />
        <Route path="/rooms/:roomId" component={Room} />
        <Route path="/rooms/create" component={CreateRoom} />
      </Content>
    </main>
  {:else}
    <Route path="/login" component={Login} />
  {/if}
</Router>

<style>
  :global(*) {
    margin: 0;
    padding: 0;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
  }
</style>

// styleguide/vue/src/App.vue
<script>
  import VueRouter from 'vue-router';
  import { CreateRoom, Rooms, Room, Login } from './pages'
  import { Header, Content } from './components'

  const user = JSON.parse(localStorage.getItem('user') || '{}')

  const router = new VueRouter({
    mode: 'history',
    routes: [
      { path: '/', name: 'home', component: Rooms },
      { path: '/rooms/create', name: 'rooms_create', component: CreateRoom },
      { path: '/rooms/:roomId', name: 'room', component: Room },
      { path: '/login', name: 'login', component: Login }
    ]
  })

  router.beforeEach((to, from, next) => {
    if (to.name !== 'login' && !user.id) next({ name: 'login' })
    if (to.name === 'login' && user.id) next({ name: 'home' })
    else next()
  })

  export default {
    router,
    name: 'app',
    components: { Header, Content },
    data: ()=> ({ user })
  }
</script>

<template>
  <div>
    <Header v-if="user.id" />
    <Content>
      <router-view />
    </Content>
  </div>
</template>

<style>
  * {
    margin: 0;
    padding: 0;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
  }
</style>
